services:
  - type: web
    name: aplyease-backend
    env: node
    buildCommand: |
      # Use backend-only package.json for smaller build
      cp package-backend.json package.json
      npm install --production
      npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
