flowchart TD
  subgraph Client
    C["Client"]
  end

  subgraph "My Applications"
    CU2["List / Filter My Applications"]
    CU4["Export My Applications (CSV)"]
  end

  subgraph Insights
    CU3["View My Stats"]
  end

  CU1["Login / Logout"]

  %% Links
  C --> CU1
  C --> CU2
  C --> CU3
  C --> CU4
